/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-04-09 03:03:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.planner;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class planForm2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:contains", org.apache.taglibs.standard.functions.Functions.class, "contains", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/workspace_plan_and_go/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/plan_and_go_Prj/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/workspace_plan_and_go/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/plan_and_go_Prj/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/workspace_plan_and_go/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/plan_and_go_Prj/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1736319838737L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- 로그인한 사용자 정보 확인 -->\r\n");

	request.setCharacterEncoding("UTF-8");
String SCHEDULE_ID = request.getParameter("SCHEDULE_ID");
String group_id = request.getParameter("group_id");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>여행 일정 플래너</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"planForm2\" style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/plan.jpeg'); background-size: cover; background-position: center;\">\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/main.do\"> \r\n");
      out.write("		<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/plan_and_go_logo.jpg\" alt=\"Plan&Go 로고\" class=\"logo\">\r\n");
      out.write("		</a> \r\n");
      out.write("		<div class=\"ml-auto\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("						\r\n");
      out.write("			<form id=\"planFormLogout\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/logout.do\" method=\"GET\">\r\n");
      out.write("				<input type=\"hidden\" name=\"MEMBER_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedInUser.MEMBER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<button class=\"btn btn-outline-primary\">로그아웃</button>\r\n");
      out.write("			</form>\r\n");
      out.write("			<!-- 로그아웃 링크 -->\r\n");
      out.write("			\r\n");
      out.write("			<form id=\"planFormLogout\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/review/list.do\" method=\"POST\">\r\n");
      out.write("				<input type=\"hidden\" name=\"MEMBER_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedInUser.MEMBER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<button class=\"btn btn-outline-secondary\">리뷰 게시판</button>\r\n");
      out.write("			</form>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<form id=\"planFormMyPage2\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/myPage.do\" method=\"POST\">\r\n");
      out.write("				<input type=\"hidden\" name=\"MEMBER_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedInUser.MEMBER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<button class=\"btn btn-outline-success\">마이페이지</button>\r\n");
      out.write("			</form>\r\n");
      out.write("						\r\n");
      out.write("			<!-- <a class=\"btn btn-outline-success\" href=\"#\" onclick=\"postToMyPage(); return false;\">마이페이지</a> -->\r\n");
      out.write("			<!-- myPage POST 요청으로 수정 -->\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container mt-5\">\r\n");
      out.write("		<h1>여행 일정 플래너</h1>\r\n");
      out.write("		<form\r\n");
      out.write("			action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planner/clearSession.do?MEMBER_ID=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedInUser.MEMBER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("			method=\"POST\">\r\n");
      out.write("			<!-- 도시 선택 -->\r\n");
      out.write("			<div class=\"mb-3\">\r\n");
      out.write("				<label for=\"region\" class=\"form-label\">여행 도시 선택</label> <select\r\n");
      out.write("					id=\"region\" name=\"region\" class=\"form-select\" required>\r\n");
      out.write("					<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 날짜 목록 -->\r\n");
      out.write("			<div class=\"list-group mt-4\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 일정 생성 버튼 -->\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("		<!-- 날짜 선택 드롭다운 -->\r\n");
      out.write("<div class=\"date-filter-container\">\r\n");
      out.write("    <label class=\"date-label\" for=\"filterDate\">날짜 선택</label>\r\n");
      out.write("    <select id=\"filterDate\" class=\"form-select date-select\" onchange=\"filterSchedule()\">\r\n");
      out.write("        <option value=\"\">전체 보기</option>\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </select>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 저장된 일정 목록 -->\r\n");
      out.write("		<div class=\"schedule-container\">\r\n");
      out.write("			<h3 class=\"mt-4\">저장된 일정</h3>\r\n");
      out.write("			<form id=\"planFormMyPage2\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/myPage.do\" method=\"POST\">\r\n");
      out.write("				<input type=\"hidden\" name=\"MEMBER_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loggedInUser.MEMBER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<button class=\"mypage-btn\">마이페이지</button>\r\n");
      out.write("			</form>\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"scheduleList\"></div>\r\n");
      out.write("		<table border=\"1\" align=\"center\" width=\"80%\" id=\"scheduleTable\">\r\n");
      out.write("			<thead>\r\n");
      out.write("				<tr align=\"center\">\r\n");
      out.write("					<td><b>날짜</b></td>\r\n");
      out.write("					<td><b>시간</b></td>\r\n");
      out.write("					<td><b>일정 제목</b></td>\r\n");
      out.write("					<td><b>방문 장소</b></td>\r\n");
      out.write("					<td><b>예상 비용</b></td>\r\n");
      out.write("					<td><b>실제 비용</b></td>\r\n");
      out.write("					<td><b>비고</b></td>\r\n");
      out.write("					<td><b>수정</b></td>\r\n");
      out.write("					<td><b>삭제</b></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 일정 모달 -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"scheduleModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"scheduleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"scheduleModalLabel\">일정 입력</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planner/saveActivity.do\" method=\"POST\">\r\n");
      out.write("						<input type=\"hidden\" id=\"region\" name=\"region\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("						<input type=\"hidden\" name=\"SCHEDULE_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${schedule_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("						<input type=\"hidden\" name=\"group_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${group_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input\r\n");
      out.write("							type=\"hidden\" name=\"start_date\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${start_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input\r\n");
      out.write("							type=\"hidden\" name=\"end_date\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${end_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("						<!-- 선택된 날짜 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"ACTIVITY_DATE\" class=\"form-label\">선택된 날짜</label> <input\r\n");
      out.write("								type=\"text\" id=\"ACTIVITY_DATE\" name=\"ACTIVITY_DATE\"\r\n");
      out.write("								class=\"form-control\" readonly>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 선택된 시간 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"scheduleTime\" class=\"form-label\">시간</label> <input\r\n");
      out.write("								type=\"time\" id=\"ACTIVITY_TIME\" name=\"ACTIVITY_TIME\"\r\n");
      out.write("								class=\"form-control\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 일정 제목 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"scheduleTitle\" class=\"form-label\">일정 제목</label> <input\r\n");
      out.write("								type=\"text\" id=\"ACTIVITY_NAME\" name=\"ACTIVITY_NAME\"\r\n");
      out.write("								class=\"form-control\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 방문 장소 선택 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"schedulePlace\" class=\"form-label\">방문 장소 선택</label>\r\n");
      out.write("							<div class=\"d-flex\">\r\n");
      out.write("								<input type=\"text\" id=\"PLACE_NAME\" name=\"PLACE_NAME\"\r\n");
      out.write("									class=\"form-control\" placeholder=\"선택된 장소\" readonly required>\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-secondary ms-2\"\r\n");
      out.write("									data-bs-toggle=\"modal\" data-bs-target=\"#placeListModal\">장소\r\n");
      out.write("									선택</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 예상 비용 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"estimatedCost\" class=\"form-label\">예상 비용</label> <input\r\n");
      out.write("								type=\"number\" id=\"EXPECTED_COST\" name=\"EXPECTED_COST\"\r\n");
      out.write("								class=\"form-control\" placeholder=\"예상 비용을 입력해주세요\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 실제 비용 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"actualCost\" class=\"form-label\">실제 비용</label> <input\r\n");
      out.write("								type=\"number\" id=\"ACTUAL_COST\" name=\"ACTUAL_COST\"\r\n");
      out.write("								class=\"form-control\" placeholder=\"실제 비용을 입력해주세요\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 비고 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"comment\" class=\"form-label\">비고</label>\r\n");
      out.write("							<textarea id=\"COMMENT\" name=\"COMMENT\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"50자 까지 입력 가능합니다.\" rows=\"4\" maxlength=\"50\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">일정 저장</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 일정 수정 모달 -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"scheduleUpdateModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"scheduleUpdateModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"scheduleUpdateModalLabel\">일정 수정</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/planner/updateActivity.do\"\r\n");
      out.write("						method=\"POST\">\r\n");
      out.write("						<input type=\"hidden\" id=\"region\" name=\"region\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("						<input type=\"hidden\" name=\"SCHEDULE_ID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${schedule_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("						<input type=\"hidden\" name=\"group_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${group_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input\r\n");
      out.write("							type=\"hidden\" name=\"start_date\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${start_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input\r\n");
      out.write("							type=\"hidden\" name=\"end_date\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${end_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input\r\n");
      out.write("							type=\"hidden\" id=\"ACTIVITY_ID\" name=\"ACTIVITY_ID\" />\r\n");
      out.write("\r\n");
      out.write("						<!-- 선택된 날짜 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"ACTIVITY_DATE\" class=\"form-label\">선택된 날짜:</label> <input\r\n");
      out.write("								type=\"text\" id=\"UPDATE_ACTIVITY_DATE\"\r\n");
      out.write("								name=\"UPDATE_ACTIVITY_DATE\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"YYYY-MM-DD\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 선택된 시간 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"scheduleTime\" class=\"form-label\">시간:</label> <input\r\n");
      out.write("								type=\"time\" id=\"UPDATE_ACTIVITY_TIME\"\r\n");
      out.write("								name=\"UPDATE_ACTIVITY_TIME\" class=\"form-control\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 일정 제목 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"scheduleTitle\" class=\"form-label\">일정 제목:</label> <input\r\n");
      out.write("								type=\"text\" id=\"UPDATE_ACTIVITY_NAME\"\r\n");
      out.write("								name=\"UPDATE_ACTIVITY_NAME\" class=\"form-control\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 방문 장소 선택 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"schedulePlace\" class=\"form-label\">방문 장소 선택:</label>\r\n");
      out.write("							<div class=\"d-flex\">\r\n");
      out.write("								<input type=\"text\" id=\"UPDATE_PLACE_NAME\"\r\n");
      out.write("									name=\"UPDATE_PLACE_NAME\" class=\"form-control\"\r\n");
      out.write("									placeholder=\"선택된 장소\" readonly required>\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-secondary ms-2\"\r\n");
      out.write("									data-bs-toggle=\"modal\" data-bs-target=\"#UpdatePlaceListModal\">장소\r\n");
      out.write("									선택</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 예상 비용 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"estimatedCost\" class=\"form-label\">예상 비용:</label> <input\r\n");
      out.write("								type=\"number\" id=\"UPDATE_EXPECTED_COST\"\r\n");
      out.write("								name=\"UPDATE_EXPECTED_COST\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"예상 비용을 입력해주세요\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 실제 비용 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"actualCost\" class=\"form-label\">실제 비용:</label> <input\r\n");
      out.write("								type=\"number\" id=\"UPDATE_ACTUAL_COST\" name=\"UPDATE_ACTUAL_COST\"\r\n");
      out.write("								class=\"form-control\" placeholder=\"실제 비용을 입력해주세요\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 비고 -->\r\n");
      out.write("						<div class=\"mb-3\">\r\n");
      out.write("							<label for=\"comment\" class=\"form-label\">비고:</label>\r\n");
      out.write("							<textarea id=\"UPDATE_COMMENT\" name=\"UPDATE_COMMENT\"\r\n");
      out.write("								class=\"form-control\" placeholder=\"50자 까지 입력 가능합니다.\" rows=\"4\"\r\n");
      out.write("								maxlength=\"50\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">일정 수정</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 장소 리스트 모달 -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"placeListModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"placeListModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"placeListModalLabel\">장소 리스트</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<!-- 🔹 검색 입력창 추가 -->\r\n");
      out.write("					<input type=\"text\" id=\"placeSearchInput\" class=\"form-control mb-3\"\r\n");
      out.write("						placeholder=\"장소 검색...\" onkeyup=\"filterPlaces()\">\r\n");
      out.write("\r\n");
      out.write("					<!-- 카테고리 버튼 -->\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<button class=\"btn btn-primary category-btn\" data-category=\"all\"\r\n");
      out.write("							data-modal=\"list\">전체</button>\r\n");
      out.write("						<button class=\"btn btn-secondary category-btn\" data-category=\"식당\"\r\n");
      out.write("							data-modal=\"list\">식당</button>\r\n");
      out.write("						<button class=\"btn btn-success category-btn\" data-category=\"관광지\"\r\n");
      out.write("							data-modal=\"list\">관광지</button>\r\n");
      out.write("						<button class=\"btn btn-warning category-btn\" data-category=\"숙소\"\r\n");
      out.write("							data-modal=\"list\">숙소</button>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 장소 리스트 -->\r\n");
      out.write("					<div class=\"row\" id=\"placeContainer\">\r\n");
      out.write("					\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 장소 수정 모달 -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"UpdatePlaceListModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"UpdatePlaceListModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"UpdatePlaceListModalLabel\">장소 리스트</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<!-- 🔹 검색 입력창 추가 -->\r\n");
      out.write("					<input type=\"text\" id=\"UpdatePlaceSearchInput\"\r\n");
      out.write("						class=\"form-control mb-3\" placeholder=\"장소 검색...\"\r\n");
      out.write("						onkeyup=\"UpdateFilterPlaces()\">\r\n");
      out.write("\r\n");
      out.write("					<!-- 카테고리 버튼 -->\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<button class=\"btn btn-primary category-btn\" data-category=\"all\"\r\n");
      out.write("							data-modal=\"update\">전체</button>\r\n");
      out.write("						<button class=\"btn btn-secondary category-btn\" data-category=\"식당\"\r\n");
      out.write("							data-modal=\"update\">식당</button>\r\n");
      out.write("						<button class=\"btn btn-success category-btn\" data-category=\"관광지\"\r\n");
      out.write("							data-modal=\"update\">관광지</button>\r\n");
      out.write("						<button class=\"btn btn-warning category-btn\" data-category=\"숙소\"\r\n");
      out.write("							data-modal=\"update\">숙소</button>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 장소 리스트 -->\r\n");
      out.write("					<div class=\"row\" id=\"updatePlaceContainer\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 장소 상세 정보 모달 -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"placeModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"placeModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"placeModalLabel\">장소 상세 정보</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<!-- 장소 상세 내용 -->\r\n");
      out.write("					<img id=\"detailImage\" src=\"\" alt=\"\" class=\"img-fluid mb-3\">\r\n");
      out.write("					<h5 id=\"detailName\"></h5>\r\n");
      out.write("					<p id=\"detailInfo\"></p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("						onclick=\"selectPlace()\">선택하기</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-bs-dismiss=\"modal\">닫기</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 장소 수정 상세 정보 모달 -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"UpdatePlaceModal\" tabindex=\"-1\"\r\n");
      out.write("		aria-labelledby=\"UpdatePlaceModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"UpdatePlaceModalLabel\">장소 상세 정보</h5>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<!-- 장소 상세 내용 -->\r\n");
      out.write("					<img id=\"updateDetailImage\" src=\"\" alt=\"\" class=\"img-fluid mb-3\">\r\n");
      out.write("					<h5 id=\"updateDetailName\"></h5>\r\n");
      out.write("					<p id=\"updateDetailInfo\"></p>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("						onclick=\"selectUpdatePlace()\">선택하기</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-bs-dismiss=\"modal\">닫기</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		let selectedPlaceName = '';\r\n");
      out.write("		let selectedDate = \"\"; // 선택된 날짜 저장 변수\r\n");
      out.write("		let datePlaceMap = {}; // 날짜별로 선택된 장소를 저장할 객체\r\n");
      out.write("		let scheduleList = []; // 저장된 일정 목록\r\n");
      out.write("\r\n");
      out.write("		const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("		if (urlParams.get(\"error\") === \"true\") {\r\n");
      out.write("			alert(\"일정 저장 중 오류가 발생했습니다.\");\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("		    let selectedCategoryList = \"all\"; // 장소 리스트 모달 기본 카테고리\r\n");
      out.write("		    let selectedCategoryUpdate = \"all\"; // 장소 수정 모달 기본 카테고리\r\n");
      out.write("\r\n");
      out.write("		    // 카테고리 버튼 클릭 이벤트 추가\r\n");
      out.write("		    document.querySelectorAll(\".category-btn\").forEach(button => {\r\n");
      out.write("		        button.addEventListener(\"click\", function () {\r\n");
      out.write("		            let category = this.getAttribute(\"data-category\");\r\n");
      out.write("		            let modalType = this.getAttribute(\"data-modal\");\r\n");
      out.write("\r\n");
      out.write("		            if (modalType === \"list\") {\r\n");
      out.write("		                selectedCategoryList = category; // 선택된 카테고리 저장\r\n");
      out.write("		                filterPlaces(selectedCategoryList);\r\n");
      out.write("		            } else if (modalType === \"update\") {\r\n");
      out.write("		                selectedCategoryUpdate = category; // 선택된 카테고리 저장\r\n");
      out.write("		                UpdateFilterPlaces(selectedCategoryUpdate);\r\n");
      out.write("		            }\r\n");
      out.write("		        });\r\n");
      out.write("		    });\r\n");
      out.write("\r\n");
      out.write("		    // 장소 리스트 모달 검색 이벤트\r\n");
      out.write("		    document.getElementById(\"placeSearchInput\").addEventListener(\"keyup\", function () {\r\n");
      out.write("		        filterPlaces(selectedCategoryList);\r\n");
      out.write("		    });\r\n");
      out.write("\r\n");
      out.write("		    // 장소 수정 모달 검색 이벤트\r\n");
      out.write("		    document.getElementById(\"UpdatePlaceSearchInput\").addEventListener(\"keyup\", function () {\r\n");
      out.write("		        UpdateFilterPlaces(selectedCategoryUpdate);\r\n");
      out.write("		    });\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		function filterSchedule() {\r\n");
      out.write("		    var selectedDate = document.getElementById(\"filterDate\").value;\r\n");
      out.write("		    var rows = document.querySelectorAll(\"#scheduleTable tbody tr\"); // 일정 목록의 각 행 가져오기\r\n");
      out.write("\r\n");
      out.write("		    rows.forEach(function(row) {\r\n");
      out.write("		        var activityDate = row.getAttribute(\"data-date\"); // 각 행의 날짜 값 가져오기\r\n");
      out.write("		        if (selectedDate === \"\" || activityDate === selectedDate) {\r\n");
      out.write("		            row.style.display = \"\"; // 선택한 날짜와 같거나 전체 보기면 표시\r\n");
      out.write("		        } else {\r\n");
      out.write("		            row.style.display = \"none\"; // 선택한 날짜와 다르면 숨김\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// 날짜 버튼 클릭 시 모달에 날짜 전달\r\n");
      out.write("		function openScheduleModal(date) {\r\n");
      out.write("\r\n");
      out.write("			selectedDate = date; // 선택한 날짜 저장\r\n");
      out.write("			console.log(selectedDate);\r\n");
      out.write("			document.getElementById(\"ACTIVITY_DATE\").value = selectedDate; // 모달의 날짜 입력 필드에 날짜 표시\r\n");
      out.write("			// 선택된 날짜에 해당하는 장소가 이미 선택되어 있으면, 해당 장소를 표시\r\n");
      out.write("			const placeName = datePlaceMap[selectedDate] || \"\";\r\n");
      out.write("			document.getElementById(\"PLACE_NAME\").value = placeName;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function openUpdateScheduleModal(date, time, act_name, plc_name, exp_cost, act_cost, act_id, comment) {\r\n");
      out.write("\r\n");
      out.write("			document.getElementById(\"UPDATE_ACTIVITY_DATE\").value = date; // 모달의 날짜 입력 필드에 날짜 표시\r\n");
      out.write("			document.getElementById(\"UPDATE_ACTIVITY_TIME\").value = time;\r\n");
      out.write("			document.getElementById(\"UPDATE_ACTIVITY_NAME\").value = act_name;\r\n");
      out.write("			document.getElementById(\"UPDATE_PLACE_NAME\").value = plc_name;\r\n");
      out.write("			document.getElementById(\"UPDATE_EXPECTED_COST\").value = exp_cost;\r\n");
      out.write("			document.getElementById(\"UPDATE_ACTUAL_COST\").value = act_cost;\r\n");
      out.write("			document.getElementById(\"ACTIVITY_ID\").value = act_id;\r\n");
      out.write("			document.getElementById(\"UPDATE_COMMENT\").value = comment;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function filterPlaces(category = \"all\") {\r\n");
      out.write("		    const input = document.getElementById(\"placeSearchInput\").value.toLowerCase();\r\n");
      out.write("		    let places = document.querySelectorAll(\"#placeContainer .place-item\");\r\n");
      out.write("\r\n");
      out.write("		    places.forEach(place => {\r\n");
      out.write("		        let placeCategory = place.getAttribute(\"data-category\");\r\n");
      out.write("		        let placeName = place.querySelector(\"h6\").textContent.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("		        let categoryMatch = (category === \"all\" || placeCategory === category);\r\n");
      out.write("		        let searchMatch = placeName.includes(input);\r\n");
      out.write("\r\n");
      out.write("		        place.style.display = (categoryMatch && searchMatch) ? \"block\" : \"none\";\r\n");
      out.write("		    });\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function UpdateFilterPlaces(category = \"all\") {\r\n");
      out.write("		    const input = document.getElementById(\"UpdatePlaceSearchInput\").value.toLowerCase();\r\n");
      out.write("		    let places = document.querySelectorAll(\"#updatePlaceContainer .update-place-item\");\r\n");
      out.write("\r\n");
      out.write("		    places.forEach(place => {\r\n");
      out.write("		        let placeCategory = place.getAttribute(\"data-category\");\r\n");
      out.write("		        let placeName = place.querySelector(\"h6\").textContent.toLowerCase();\r\n");
      out.write("\r\n");
      out.write("		        let categoryMatch = (category === \"all\" || placeCategory === category);\r\n");
      out.write("		        let searchMatch = placeName.includes(input);\r\n");
      out.write("\r\n");
      out.write("		        place.style.display = (categoryMatch && searchMatch) ? \"block\" : \"none\";\r\n");
      out.write("		    });\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		// 장소 상세 정보 모달에 표시\r\n");
      out.write("		function showPlaceDetails(name, image, info) {\r\n");
      out.write("			let imagePath = image.startsWith(\"http\") ? image : `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plan_and_go_image/place_image/` + image + `.jpg`;\r\n");
      out.write("			document.getElementById(\"detailName\").textContent = name;\r\n");
      out.write("			document.getElementById(\"detailImage\").src = imagePath;\r\n");
      out.write("			document.getElementById(\"detailInfo\").textContent = info;\r\n");
      out.write("			selectedPlaceName = name;\r\n");
      out.write("\r\n");
      out.write("			// 장소 상세 정보 모달 열기\r\n");
      out.write("			const placeModal = new bootstrap.Modal(document\r\n");
      out.write("					.getElementById('placeModal'));\r\n");
      out.write("			placeModal.show();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function UpdateShowPlaceDetails(name, image, info) {\r\n");
      out.write("			let imagePath = image.startsWith(\"http\") ? image : `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plan_and_go_image/place_image/` + image + `.jpg`;\r\n");
      out.write("			document.getElementById(\"updateDetailName\").textContent = name;\r\n");
      out.write("			document.getElementById(\"updateDetailImage\").src = imagePath;\r\n");
      out.write("			document.getElementById(\"updateDetailInfo\").textContent = info;\r\n");
      out.write("			selectedPlaceName = name;\r\n");
      out.write("\r\n");
      out.write("			// 장소 상세 정보 모달 열기\r\n");
      out.write("			const placeModal = new bootstrap.Modal(document\r\n");
      out.write("					.getElementById('UpdatePlaceModal'));\r\n");
      out.write("			placeModal.show();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// 장소 선택 함수\r\n");
      out.write("		function selectPlace() {\r\n");
      out.write("			if (!selectedPlaceName) {\r\n");
      out.write("				alert(\"장소를 선택해주세요.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 선택된 장소를 일정 모달에 반영\r\n");
      out.write("			document.getElementById(\"PLACE_NAME\").value = selectedPlaceName;\r\n");
      out.write("\r\n");
      out.write("			// 장소 리스트 모달 닫기\r\n");
      out.write("			const placeModal = bootstrap.Modal.getInstance(document\r\n");
      out.write("					.getElementById('placeModal'));\r\n");
      out.write("			const placeListModal = bootstrap.Modal.getInstance(document\r\n");
      out.write("					.getElementById('placeListModal'));\r\n");
      out.write("\r\n");
      out.write("			if (placeModal)\r\n");
      out.write("				placeModal.hide();\r\n");
      out.write("			if (placeListModal)\r\n");
      out.write("				placeListModal.hide();\r\n");
      out.write("\r\n");
      out.write("			// 일정 입력 모달 열기\r\n");
      out.write("			const scheduleModal = new bootstrap.Modal(document\r\n");
      out.write("					.getElementById('scheduleModal'));\r\n");
      out.write("			scheduleModal.show();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// 장소 수정 함수\r\n");
      out.write("		function selectUpdatePlace() {\r\n");
      out.write("			if (!selectedPlaceName) {\r\n");
      out.write("				alert(\"장소를 선택해주세요.\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// 선택된 장소를 일정 모달에 반영\r\n");
      out.write("			document.getElementById(\"UPDATE_PLACE_NAME\").value = selectedPlaceName;\r\n");
      out.write("\r\n");
      out.write("			// 장소 리스트 모달 닫기\r\n");
      out.write("			const placeModal = bootstrap.Modal.getInstance(document\r\n");
      out.write("					.getElementById('UpdatePlaceModal'));\r\n");
      out.write("			const placeListModal = bootstrap.Modal.getInstance(document\r\n");
      out.write("					.getElementById('UpdatePlaceListModal'));\r\n");
      out.write("\r\n");
      out.write("			if (placeModal)\r\n");
      out.write("				placeModal.hide();\r\n");
      out.write("			if (placeListModal)\r\n");
      out.write("				placeListModal.hide();\r\n");
      out.write("\r\n");
      out.write("			// 일정 입력 모달 열기\r\n");
      out.write("			const scheduleModal = new bootstrap.Modal(document\r\n");
      out.write("					.getElementById('scheduleUpdateModal'));\r\n");
      out.write("			scheduleModal.show();\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/planner/planForm2.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("contextPath");
    // /WEB-INF/views/planner/planForm2.jsp(11,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/planner/planForm2.jsp(11,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/views/planner/planForm2.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("loggedInUser");
    // /WEB-INF/views/planner/planForm2.jsp(12,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/planner/planForm2.jsp(12,0) '${sessionScope.member}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.member}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/planner/planForm2.jsp(80,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/planner/planForm2.jsp(80,4) '${dateList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dateList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/planner/planForm2.jsp(80,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("dl");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<button type=\"button\"\r\n");
          out.write("						class=\"list-group-item list-group-item-action\"\r\n");
          out.write("						data-bs-toggle=\"modal\" data-bs-target=\"#scheduleModal\"\r\n");
          out.write("						onclick=\"openScheduleModal('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</button>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /WEB-INF/views/planner/planForm2.jsp(97,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("uniqueDates");
    // /WEB-INF/views/planner/planForm2.jsp(97,8) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/planner/planForm2.jsp(97,8) ''",_jsp_getExpressionFactory().createValueExpression("",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/planner/planForm2.jsp(98,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("activityFilter");
    // /WEB-INF/views/planner/planForm2.jsp(98,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/planner/planForm2.jsp(98,8) '${activityList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${activityList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fset_005f3(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/views/planner/planForm2.jsp(99,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setVar("formattedDate");
    int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
    if (_jspx_eval_c_005fset_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_c_005fset_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        _jspx_push_body_count_c_005fforEach_005f1[0]++;
        out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f3);
      }
      do {
        out.write("\r\n");
        out.write("                ");
        if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fset_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
          return true;
        out.write("\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fset_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_c_005fset_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
        _jspx_push_body_count_c_005fforEach_005f1[0]--;
      }
    }
    if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f3);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f3);
    // /WEB-INF/views/planner/planForm2.jsp(100,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activityFilter.ACTIVITY_DATE}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/planner/planForm2.jsp(100,16) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/views/planner/planForm2.jsp(102,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not fn:contains(uniqueDates, formattedDate)}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                <option value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formattedDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('"');
        out.write('>');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formattedDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</option>\r\n");
        out.write("                ");
        if (_jspx_meth_c_005fset_005f4(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
          return true;
        out.write("\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/views/planner/planForm2.jsp(104,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f4.setVar("uniqueDates");
    // /WEB-INF/views/planner/planForm2.jsp(104,16) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/planner/planForm2.jsp(104,16) '${uniqueDates},${formattedDate}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${uniqueDates},${formattedDate}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
    if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /WEB-INF/views/planner/planForm2.jsp(137,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("activity");
    // /WEB-INF/views/planner/planForm2.jsp(137,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/planner/planForm2.jsp(137,4) '${activityList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${activityList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<tr align=\"center\"\r\n");
          out.write("						data-date=\"");
          if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
            return true;
          out.write("\">\r\n");
          out.write("						<td>");
          if (_jspx_meth_fmt_005fformatDate_005f2(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
            return true;
          out.write("</td>\r\n");
          out.write("						<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTIVITY_TIME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("						<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTIVITY_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("						<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.PLACE_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("						<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.EXPECTED_COST}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("						<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTUAL_COST}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("						<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.COMMENT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("						<td><button type=\"button\" class=\"btn btn-primary\"\r\n");
          out.write("								data-bs-toggle=\"modal\" data-bs-target=\"#scheduleUpdateModal\"\r\n");
          out.write("								onclick=\"openUpdateScheduleModal('");
          if (_jspx_meth_fmt_005fformatDate_005f3(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
            return true;
          out.write("', \r\n");
          out.write("		                        '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTIVITY_TIME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTIVITY_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', \r\n");
          out.write("		                        '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.PLACE_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.EXPECTED_COST}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', \r\n");
          out.write("		                        '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTUAL_COST}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTIVITY_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("',\r\n");
          out.write("		                        '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.COMMENT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">수정하기</button>\r\n");
          out.write("						</td>\r\n");
          out.write("						<td>\r\n");
          out.write("							<form action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/planner/removeActivity.do\"\r\n");
          out.write("								method=\"post\" onsubmit=\"return confirm('정말 삭제하시겠습니까?');\">\r\n");
          out.write("								<input type=\"hidden\" name=\"region\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${region}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<input type=\"hidden\" name=\"start_date\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${start_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<input type=\"hidden\" name=\"end_date\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${end_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<input type=\"hidden\" name=\"group_id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${group_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<input type=\"hidden\" name=\"schedule_id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${schedule_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<input type=\"hidden\" name=\"ACTIVITY_ID\"\r\n");
          out.write("									value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTIVITY_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<button type=\"submit\" class=\"btn btn-danger\">삭제하기</button>\r\n");
          out.write("							</form>\r\n");
          out.write("						</td>\r\n");
          out.write("					</tr>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
    // /WEB-INF/views/planner/planForm2.jsp(139,17) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTIVITY_DATE}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/planner/planForm2.jsp(139,17) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy-MM-dd");
    int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f2.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
    // /WEB-INF/views/planner/planForm2.jsp(140,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f2.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTIVITY_DATE}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/planner/planForm2.jsp(140,10) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f2.setPattern("yyyy-MM-dd");
    int _jspx_eval_fmt_005fformatDate_005f2 = _jspx_th_fmt_005fformatDate_005f2.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f2);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f3.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
    // /WEB-INF/views/planner/planForm2.jsp(150,42) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f3.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${activity.ACTIVITY_DATE}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/planner/planForm2.jsp(150,42) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f3.setPattern("yyyy-MM-dd");
    int _jspx_eval_fmt_005fformatDate_005f3 = _jspx_th_fmt_005fformatDate_005f3.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /WEB-INF/views/planner/planForm2.jsp(371,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/planner/planForm2.jsp(371,6) '${place}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${place}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/planner/planForm2.jsp(371,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("placeList");
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<div class=\"mb-3 place-item\"\r\n");
          out.write("								data-category=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${placeList.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<img\r\n");
          out.write("									src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/plan_and_go_image/place_image/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${placeList.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(".jpg\"\r\n");
          out.write("									alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${placeList.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"img-fluid\"\r\n");
          out.write("									style=\"cursor: pointer;\"\r\n");
          out.write("									onclick=\"showPlaceDetails('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${placeList.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${placeList.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${placeList.info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">\r\n");
          out.write("								<h6>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${placeList.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h6>\r\n");
          out.write("							</div>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f4.setParent(null);
    // /WEB-INF/views/planner/planForm2.jsp(418,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/planner/planForm2.jsp(418,6) '${place}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${place}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/planner/planForm2.jsp(418,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setVar("UpdatePlaceList");
    int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
      if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<div class=\"mb-3 update-place-item\"\r\n");
          out.write("								data-category=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UpdatePlaceList.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<img\r\n");
          out.write("									src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/plan_and_go_image/place_image/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UpdatePlaceList.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(".jpg\"\r\n");
          out.write("									alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UpdatePlaceList.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"img-fluid\"\r\n");
          out.write("									style=\"cursor: pointer;\"\r\n");
          out.write("									onclick=\"UpdateShowPlaceDetails('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UpdatePlaceList.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UpdatePlaceList.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("', '");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UpdatePlaceList.info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("')\">\r\n");
          out.write("								<h6>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UpdatePlaceList.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h6>\r\n");
          out.write("							</div>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f4.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
    return false;
  }
}
